"""Provenance Guard — AI content attribution backend.

Milestone 3: Flask app + Groq detection signal (Signal 1) + audit log.
Confidence scoring (M4) and transparency labels (M5) are stubbed for now.
"""

import json
import os
import uuid
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from groq import Groq

load_dotenv()

app = Flask(__name__)

# --- Configuration ---------------------------------------------------------

LOG_PATH = os.path.join(os.path.dirname(__file__), "logs", "audit.jsonl")
GROQ_MODEL = "llama-3.3-70b-versatile"

_groq_client = None


def get_groq_client():
    """Lazily create a single Groq client so import never fails without a key."""
    global _groq_client
    if _groq_client is None:
        _groq_client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _groq_client


# --- Detection Signal 1: Groq LLM ------------------------------------------

LLM_SYSTEM_PROMPT = (
    "You are a forensic writing analyst. Estimate how likely a passage of text "
    "was generated by an AI language model versus written by a human. Consider "
    "stylistic uniformity, tone, coherence, repetition, and phrasing patterns. "
    "Respond ONLY with a JSON object of the form "
    '{"ai_probability": <float 0.0-1.0>, "reasoning": "<one short sentence>"}. '
    "0.0 means almost certainly human, 1.0 means almost certainly AI-generated. "
    "When evidence is weak (e.g. very short text), stay near 0.5."
)


def llm_signal(text):
    """Signal 1 — Groq LLM judgment.

    Returns a float in [0.0, 1.0]; higher means more AI-like.
    """
    client = get_groq_client()
    response = client.chat.completions.create(
        model=GROQ_MODEL,
        temperature=0,
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": LLM_SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
    )
    data = json.loads(response.choices[0].message.content)
    score = float(data["ai_probability"])
    return max(0.0, min(1.0, score))


# --- Audit log (structured JSON Lines) -------------------------------------

def write_log(entry):
    """Append one structured entry to the JSONL audit log."""
    os.makedirs(os.path.dirname(LOG_PATH), exist_ok=True)
    with open(LOG_PATH, "a") as f:
        f.write(json.dumps(entry) + "\n")


def read_log(limit=50):
    """Return the most recent log entries, newest first."""
    if not os.path.exists(LOG_PATH):
        return []
    with open(LOG_PATH) as f:
        entries = [json.loads(line) for line in f if line.strip()]
    return entries[-limit:][::-1]


# --- Routes ----------------------------------------------------------------

@app.route("/submit", methods=["POST"])
def submit():
    data = request.get_json(silent=True) or {}
    text = data.get("text")
    creator_id = data.get("creator_id")

    if not text or not isinstance(text, str) or not text.strip():
        return jsonify({"error": "A non-empty 'text' field is required."}), 400
    if not creator_id:
        return jsonify({"error": "A 'creator_id' field is required."}), 400

    content_id = str(uuid.uuid4())
    llm_score = llm_signal(text)

    # M3 placeholders — real combined scoring (M4) and labels (M5) come later.
    confidence = round(llm_score, 4)
    if llm_score >= 0.70:
        attribution = "likely_ai"
    elif llm_score <= 0.30:
        attribution = "likely_human"
    else:
        attribution = "uncertain"
    label = "PLACEHOLDER — transparency label is added in Milestone 5."

    entry = {
        "event_type": "submission",
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "llm_score": round(llm_score, 4),
        "attribution": attribution,
        "confidence": confidence,
        "status": "classified",
    }
    write_log(entry)

    return jsonify({
        "content_id": content_id,
        "creator_id": creator_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
        "signals": {"llm_score": round(llm_score, 4)},
        "status": "classified",
    })


@app.route("/log", methods=["GET"])
def get_log():
    return jsonify({"entries": read_log()})


if __name__ == "__main__":
    # Port is configurable so it can avoid conflicts (e.g. macOS AirPlay on 5000).
    port = int(os.environ.get("PORT", 5000))
    app.run(debug=True, port=port)
