"""Provenance Guard — AI content attribution backend.

Milestone 3: Flask app + Groq detection signal (Signal 1) + audit log.
Confidence scoring (M4) and transparency labels (M5) are stubbed for now.
"""

import json
import os
import re
import statistics
import uuid
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from groq import Groq

load_dotenv()

app = Flask(__name__)

# --- Configuration ---------------------------------------------------------

LOG_PATH = os.path.join(os.path.dirname(__file__), "logs", "audit.jsonl")
GROQ_MODEL = "llama-3.3-70b-versatile"

_groq_client = None


def get_groq_client():
    """Lazily create a single Groq client so import never fails without a key."""
    global _groq_client
    if _groq_client is None:
        _groq_client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _groq_client


# --- Detection Signal 1: Groq LLM ------------------------------------------

LLM_SYSTEM_PROMPT = (
    "You are a forensic writing analyst. Estimate how likely a passage of text "
    "was generated by an AI language model versus written by a human. Consider "
    "stylistic uniformity, tone, coherence, repetition, and phrasing patterns. "
    "Respond ONLY with a JSON object of the form "
    '{"ai_probability": <float 0.00-1.00>, "reasoning": "<one short sentence>"}. '
    "Use the FULL range with two-decimal precision; do not default to round "
    "numbers. Scale of meaning: "
    "0.85-1.00 = clear AI hallmarks (formulaic transitions like 'Firstly/Moreover/"
    "In conclusion', uniform sentence structure, generic hedging, no personal voice); "
    "0.55-0.84 = leans AI but not certain; "
    "0.30-0.54 = genuinely ambiguous; "
    "0.15-0.29 = leans human; "
    "0.00-0.14 = clear human hallmarks (personal anecdote, idiosyncratic voice, "
    "informal punctuation, small errors). "
    "When evidence is weak (e.g. very short text), stay near 0.50."
)


def llm_signal(text):
    """Signal 1 — Groq LLM judgment.

    Returns a float in [0.0, 1.0]; higher means more AI-like.
    """
    client = get_groq_client()
    response = client.chat.completions.create(
        model=GROQ_MODEL,
        temperature=0,
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": LLM_SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
    )
    data = json.loads(response.choices[0].message.content)
    score = float(data["ai_probability"])
    return max(0.0, min(1.0, score))


# --- Detection Signal 2: Stylometric heuristics ----------------------------
#
# This signal is fully independent of the LLM: it measures *structural*
# properties of the text rather than meaning. AI prose tends to be uniform and
# polished; human writing is more variable. Higher score => more AI-like.

_STRUCTURAL_PUNCT = set(",;:—-()\"")


def _clamp(value, lo=0.0, hi=1.0):
    return max(lo, min(hi, value))


def _split_sentences(text):
    return [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]


def _words(text):
    return re.findall(r"\b\w+\b", text.lower())


def heuristic_breakdown(text):
    """Compute the stylometric sub-metrics and the combined heuristic score.

    Returns a dict so the individual metrics can be inspected and logged.
    """
    sentences = _split_sentences(text)
    words = _words(text)
    n_words = len(words)

    # Metric 1 — sentence-length variation (burstiness).
    # Humans vary sentence length; AI text is uniform. Low CV => AI-like.
    sent_lengths = [len(_words(s)) for s in sentences] or [n_words]
    mean_len = statistics.mean(sent_lengths)
    if len(sent_lengths) > 1 and mean_len > 0:
        cv = statistics.pstdev(sent_lengths) / mean_len
    else:
        cv = 0.0  # single sentence -> treat as maximally uniform
    uniformity = _clamp((0.7 - cv) / 0.6)  # cv>=0.7 -> 0 (human), cv<=0.1 -> ~1 (AI)

    # Metric 2 — vocabulary diversity (type-token ratio), windowed to the first
    # 100 words to blunt length sensitivity. Lower diversity reads as more AI-like.
    window = words[:100]
    ttr = len(set(window)) / len(window) if window else 0.0
    low_diversity = _clamp((0.85 - ttr) / 0.45)  # ttr>=0.85 -> 0, ttr<=0.4 -> 1

    # Metric 3 — structural punctuation density (commas, semicolons, dashes,
    # parentheticals per word). Formal/AI prose uses more; casual writing less.
    punct_count = sum(1 for c in text if c in _STRUCTURAL_PUNCT)
    density = punct_count / n_words if n_words else 0.0
    punctuation = _clamp(density / 0.12)  # ~0.12 marks/word and up reads as AI-like

    score = 0.55 * uniformity + 0.20 * low_diversity + 0.25 * punctuation
    return {
        "heuristic_score": round(score, 4),
        "sentence_length_cv": round(cv, 4),
        "uniformity_subscore": round(uniformity, 4),
        "type_token_ratio": round(ttr, 4),
        "low_diversity_subscore": round(low_diversity, 4),
        "punctuation_density": round(density, 4),
        "punctuation_subscore": round(punctuation, 4),
    }


def heuristic_signal(text):
    """Signal 2 — returns a float in [0.0, 1.0]; higher means more AI-like."""
    return heuristic_breakdown(text)["heuristic_score"]


# --- Confidence scoring -----------------------------------------------------

LLM_WEIGHT = 0.65
HEURISTIC_WEIGHT = 0.35


def combine_scores(llm_score, heuristic_score):
    """Combine both signals into a single confidence score and attribution.

    The LLM carries more weight because it captures semantic/stylistic nuance
    the heuristics cannot; the heuristic adds an independent structural check.
    """
    combined = LLM_WEIGHT * llm_score + HEURISTIC_WEIGHT * heuristic_score
    if combined >= 0.70:
        attribution = "likely_ai"
    elif combined <= 0.30:
        attribution = "likely_human"
    else:
        attribution = "uncertain"
    return round(combined, 4), attribution


# --- Audit log (structured JSON Lines) -------------------------------------

def write_log(entry):
    """Append one structured entry to the JSONL audit log."""
    os.makedirs(os.path.dirname(LOG_PATH), exist_ok=True)
    with open(LOG_PATH, "a") as f:
        f.write(json.dumps(entry) + "\n")


def read_log(limit=50):
    """Return the most recent log entries, newest first."""
    if not os.path.exists(LOG_PATH):
        return []
    with open(LOG_PATH) as f:
        entries = [json.loads(line) for line in f if line.strip()]
    return entries[-limit:][::-1]


# --- Routes ----------------------------------------------------------------

@app.route("/submit", methods=["POST"])
def submit():
    data = request.get_json(silent=True) or {}
    text = data.get("text")
    creator_id = data.get("creator_id")

    if not text or not isinstance(text, str) or not text.strip():
        return jsonify({"error": "A non-empty 'text' field is required."}), 400
    if not creator_id:
        return jsonify({"error": "A 'creator_id' field is required."}), 400

    content_id = str(uuid.uuid4())
    llm_score = llm_signal(text)
    heuristic_score = heuristic_signal(text)
    confidence, attribution = combine_scores(llm_score, heuristic_score)

    # M5 placeholder — the transparency label is built in Milestone 5.
    label = "PLACEHOLDER — transparency label is added in Milestone 5."

    entry = {
        "event_type": "submission",
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "llm_score": round(llm_score, 4),
        "heuristic_score": round(heuristic_score, 4),
        "confidence": confidence,
        "attribution": attribution,
        "status": "classified",
    }
    write_log(entry)

    return jsonify({
        "content_id": content_id,
        "creator_id": creator_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
        "signals": {
            "llm_score": round(llm_score, 4),
            "heuristic_score": round(heuristic_score, 4),
        },
        "status": "classified",
    })


@app.route("/log", methods=["GET"])
def get_log():
    return jsonify({"entries": read_log()})


if __name__ == "__main__":
    # Port is configurable so it can avoid conflicts (e.g. macOS AirPlay on 5000).
    port = int(os.environ.get("PORT", 5000))
    app.run(debug=True, port=port)
